export const KPI_ICON_OPTIONS = [
  { value: "auto", label: "Automatic" },
  { value: "person", label: "Person" },
  { value: "team", label: "Team" },
  { value: "briefcase", label: "Briefcase" },
  { value: "building", label: "Building" },
  { value: "store", label: "Store" },
  { value: "money", label: "Money" },
  { value: "wallet", label: "Wallet" },
  { value: "credit-card", label: "Credit card" },
  { value: "chart", label: "Chart" },
  { value: "trend", label: "Growth trend" },
  { value: "target", label: "Target" },
  { value: "shipping-box", label: "Shipping box" },
  { value: "inventory", label: "Inventory" },
  { value: "truck", label: "Truck" },
  { value: "cart", label: "Shopping cart" },
  { value: "phone", label: "Phone" },
  { value: "email", label: "Email" },
  { value: "calendar", label: "Calendar" },
  { value: "clock", label: "Clock" },
  { value: "check", label: "Completed" },
  { value: "alert", label: "Alert" },
  { value: "shield", label: "Security" },
  { value: "healthcare", label: "Healthcare" },
  { value: "education", label: "Education" },
  { value: "factory", label: "Factory" },
  { value: "tools", label: "Tools" },
  { value: "sustainability", label: "Sustainability" },
  { value: "robot-ai", label: "Robot / AI" },
  { value: "globe", label: "Global" },
  { value: "location", label: "Location" },
  { value: "map", label: "Map" },
  { value: "plane", label: "Air travel" },
  { value: "ship", label: "Ocean shipping" },
  { value: "train", label: "Rail" },
  { value: "car", label: "Automotive" },
  { value: "megaphone", label: "Marketing" },
  { value: "handshake", label: "Partnership" },
  { value: "trophy", label: "Achievement" },
  { value: "star", label: "Favorite" },
  { value: "thumbs-up", label: "Approval" },
  { value: "lightbulb", label: "Idea" },
  { value: "search", label: "Search" },
  { value: "filter", label: "Filter" },
  { value: "database", label: "Database" },
  { value: "server", label: "Server" },
  { value: "cloud", label: "Cloud" },
  { value: "lock", label: "Lock" },
  { value: "key", label: "Access" },
  { value: "document", label: "Document" },
  { value: "clipboard", label: "Checklist" },
  { value: "presentation", label: "Presentation" },
  { value: "calculator", label: "Calculator" },
  { value: "receipt", label: "Receipt" },
  { value: "banknote", label: "Banknote" },
  { value: "coins", label: "Coins" },
  { value: "percent", label: "Percentage" },
  { value: "headset", label: "Customer support" },
  { value: "video", label: "Video" },
  { value: "camera", label: "Camera" },
] as const;

export type KpiIconName = (typeof KPI_ICON_OPTIONS)[number]["value"];

export const KPI_ICON_NAMES = KPI_ICON_OPTIONS.map(
  ({ value }) => value,
) as KpiIconName[];
