import {
  BadgeCheck,
  Banknote,
  Bot,
  Boxes,
  BriefcaseBusiness,
  Building2,
  Calculator,
  CalendarDays,
  Camera,
  Car,
  ChartNoAxesColumnIncreasing,
  CircleDollarSign,
  ClipboardList,
  Clock3,
  Cloud,
  Coins,
  CreditCard,
  Database,
  Factory,
  FileText,
  Filter,
  Gauge,
  Globe2,
  GraduationCap,
  Handshake,
  Headset,
  HeartPulse,
  KeyRound,
  Leaf,
  Lightbulb,
  LockKeyhole,
  Mail,
  Map,
  MapPin,
  Megaphone,
  Package,
  Percent,
  Phone,
  Plane,
  Presentation,
  ReceiptText,
  Search,
  Server,
  ShieldCheck,
  Ship,
  ShoppingCart,
  Star,
  Store,
  Target,
  ThumbsUp,
  TrainFront,
  TrendingUp,
  TriangleAlert,
  Truck,
  Trophy,
  User,
  Users,
  Video,
  WalletCards,
  Wrench,
  type LucideIcon,
} from "lucide-react";
import { KPI_ICON_OPTIONS, type KpiIconName } from "../../domain/kpiIcons";

const KPI_ICON_COMPONENTS: Record<KpiIconName, LucideIcon> = {
  auto: Gauge,
  person: User,
  team: Users,
  briefcase: BriefcaseBusiness,
  building: Building2,
  store: Store,
  money: CircleDollarSign,
  wallet: WalletCards,
  "credit-card": CreditCard,
  chart: ChartNoAxesColumnIncreasing,
  trend: TrendingUp,
  target: Target,
  "shipping-box": Package,
  inventory: Boxes,
  truck: Truck,
  cart: ShoppingCart,
  phone: Phone,
  email: Mail,
  calendar: CalendarDays,
  clock: Clock3,
  check: BadgeCheck,
  alert: TriangleAlert,
  shield: ShieldCheck,
  healthcare: HeartPulse,
  education: GraduationCap,
  factory: Factory,
  tools: Wrench,
  sustainability: Leaf,
  "robot-ai": Bot,
  globe: Globe2,
  location: MapPin,
  map: Map,
  plane: Plane,
  ship: Ship,
  train: TrainFront,
  car: Car,
  megaphone: Megaphone,
  handshake: Handshake,
  trophy: Trophy,
  star: Star,
  "thumbs-up": ThumbsUp,
  lightbulb: Lightbulb,
  search: Search,
  filter: Filter,
  database: Database,
  server: Server,
  cloud: Cloud,
  lock: LockKeyhole,
  key: KeyRound,
  document: FileText,
  clipboard: ClipboardList,
  presentation: Presentation,
  calculator: Calculator,
  receipt: ReceiptText,
  banknote: Banknote,
  coins: Coins,
  percent: Percent,
  headset: Headset,
  video: Video,
  camera: Camera,
};

export const KPI_ICON_LIBRARY = KPI_ICON_OPTIONS.map((option) => ({
  ...option,
  Icon: KPI_ICON_COMPONENTS[option.value],
}));

export function getKpiIcon(icon: KpiIconName | undefined): LucideIcon {
  return KPI_ICON_COMPONENTS[icon ?? "auto"] ?? Gauge;
}
